name: lint-and-format
run-name: ${{ github.actor }} is pushing code
on: [push]
jobs:
    check-formatting:
        name: "Run Prettier"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
            - run: bun install
            - run: bun fmt:check
    lint:
        name: "Run ESLint"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
            - run: bun install
            - run: bun lint
